// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/protocol/vo/role.proto

package vo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色信息
type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 学校Id
	// @gotags: json:"schoolId,string"
	SchoolId int64 `protobuf:"varint,2,opt,name=school_id,json=schoolId,proto3" json:"schoolId,string"`
	// 角色Id
	// @gotags: json:"roleId,string"
	Id int64 `protobuf:"varint,3,opt,name=id,proto3" json:"roleId,string"`
	// 角色名
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// 是否为后台角色
	// @gotags: json:"isBackend"
	IsBackend bool `protobuf:"varint,5,opt,name=is_backend,json=isBackend,proto3" json:"isBackend"`
	// 是否为自定义角色
	// @gotags: json:"isDefault"
	IsDefault bool `protobuf:"varint,6,opt,name=is_default,json=isDefault,proto3" json:"isDefault"`
	// 用户数
	// @gotags: json:"userCount"
	UserCount int32 `protobuf:"varint,7,opt,name=user_count,json=userCount,proto3" json:"userCount"`
	// 创建时间
	// @gotags: json:"createdAt"
	Created string `protobuf:"bytes,8,opt,name=created,proto3" json:"createdAt"`
	// 更新时间
	// @gotags: json:"updatedAt"
	Updated string `protobuf:"bytes,9,opt,name=updated,proto3" json:"updatedAt"`
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_vo_role_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_vo_role_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_relo_protocol_vo_role_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *Role) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetIsBackend() bool {
	if x != nil {
		return x.IsBackend
	}
	return false
}

func (x *Role) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Role) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *Role) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Role) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

var File_relo_protocol_vo_role_proto protoreflect.FileDescriptor

var file_relo_protocol_vo_role_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x76, 0x6f, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x72,
	0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x6f, 0x22,
	0xd8, 0x01, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x6f,
	0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x63, 0x68,
	0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69,
	0x73, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76, 0x6f, 0x3b, 0x76,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_protocol_vo_role_proto_rawDescOnce sync.Once
	file_relo_protocol_vo_role_proto_rawDescData = file_relo_protocol_vo_role_proto_rawDesc
)

func file_relo_protocol_vo_role_proto_rawDescGZIP() []byte {
	file_relo_protocol_vo_role_proto_rawDescOnce.Do(func() {
		file_relo_protocol_vo_role_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_protocol_vo_role_proto_rawDescData)
	})
	return file_relo_protocol_vo_role_proto_rawDescData
}

var file_relo_protocol_vo_role_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_relo_protocol_vo_role_proto_goTypes = []interface{}{
	(*Role)(nil), // 0: relo.protocol.vo.Role
}
var file_relo_protocol_vo_role_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relo_protocol_vo_role_proto_init() }
func file_relo_protocol_vo_role_proto_init() {
	if File_relo_protocol_vo_role_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relo_protocol_vo_role_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_protocol_vo_role_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_protocol_vo_role_proto_goTypes,
		DependencyIndexes: file_relo_protocol_vo_role_proto_depIdxs,
		MessageInfos:      file_relo_protocol_vo_role_proto_msgTypes,
	}.Build()
	File_relo_protocol_vo_role_proto = out.File
	file_relo_protocol_vo_role_proto_rawDesc = nil
	file_relo_protocol_vo_role_proto_goTypes = nil
	file_relo_protocol_vo_role_proto_depIdxs = nil
}
