// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/protocol/vo/switch_item.proto

package vo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 讲次顺序切换信息
type SwitchItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 讲次编号
	// @gotags: json:"id,string"
	Id int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,string"`
	// 课程Id
	// @gotags: json:"parentId,string"
	ParentId int64 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parentId,string"`
	// 顺序
	// @gotags: json:"sequence" validate:"required"
	Sequence int32 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence" validate:"required"`
}

func (x *SwitchItem) Reset() {
	*x = SwitchItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_vo_switch_item_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchItem) ProtoMessage() {}

func (x *SwitchItem) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_vo_switch_item_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchItem.ProtoReflect.Descriptor instead.
func (*SwitchItem) Descriptor() ([]byte, []int) {
	return file_relo_protocol_vo_switch_item_proto_rawDescGZIP(), []int{0}
}

func (x *SwitchItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SwitchItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *SwitchItem) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_relo_protocol_vo_switch_item_proto protoreflect.FileDescriptor

var file_relo_protocol_vo_switch_item_proto_rawDesc = []byte{
	0x0a, 0x22, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x76, 0x6f, 0x2f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x6f, 0x22, 0x55, 0x0a, 0x0a, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x25, 0x5a,
	0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76,
	0x6f, 0x3b, 0x76, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_protocol_vo_switch_item_proto_rawDescOnce sync.Once
	file_relo_protocol_vo_switch_item_proto_rawDescData = file_relo_protocol_vo_switch_item_proto_rawDesc
)

func file_relo_protocol_vo_switch_item_proto_rawDescGZIP() []byte {
	file_relo_protocol_vo_switch_item_proto_rawDescOnce.Do(func() {
		file_relo_protocol_vo_switch_item_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_protocol_vo_switch_item_proto_rawDescData)
	})
	return file_relo_protocol_vo_switch_item_proto_rawDescData
}

var file_relo_protocol_vo_switch_item_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_relo_protocol_vo_switch_item_proto_goTypes = []interface{}{
	(*SwitchItem)(nil), // 0: relo.protocol.vo.SwitchItem
}
var file_relo_protocol_vo_switch_item_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relo_protocol_vo_switch_item_proto_init() }
func file_relo_protocol_vo_switch_item_proto_init() {
	if File_relo_protocol_vo_switch_item_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relo_protocol_vo_switch_item_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_protocol_vo_switch_item_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_protocol_vo_switch_item_proto_goTypes,
		DependencyIndexes: file_relo_protocol_vo_switch_item_proto_depIdxs,
		MessageInfos:      file_relo_protocol_vo_switch_item_proto_msgTypes,
	}.Build()
	File_relo_protocol_vo_switch_item_proto = out.File
	file_relo_protocol_vo_switch_item_proto_rawDesc = nil
	file_relo_protocol_vo_switch_item_proto_goTypes = nil
	file_relo_protocol_vo_switch_item_proto_depIdxs = nil
}
