// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/protocol/schooluser/add.proto

package schooluser

import (
	schooluser "github.com/reloclass/core/schooluser"
	vo "github.com/reloclass/protocol/vo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加学校用户请求
type AddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户
	// @gotags: json:"users"
	Users []*vo.SchoolUser `protobuf:"bytes,2,rep,name=users,proto3" json:"users"`
	// 代注册
	// @gotags:  json:"register" validate:"omitempty,required_with= 0 1"
	Register schooluser.RegistrationType `protobuf:"varint,3,opt,name=register,proto3,enum=relo.core.schooluser.RegistrationType" json:"register" validate:"omitempty,required_with= 0 1"`
}

func (x *AddReq) Reset() {
	*x = AddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_schooluser_add_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReq) ProtoMessage() {}

func (x *AddReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_schooluser_add_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReq.ProtoReflect.Descriptor instead.
func (*AddReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_schooluser_add_proto_rawDescGZIP(), []int{0}
}

func (x *AddReq) GetUsers() []*vo.SchoolUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *AddReq) GetRegister() schooluser.RegistrationType {
	if x != nil {
		return x.Register
	}
	return schooluser.RegistrationType_YES
}

// 添加学校用户响应
type AddRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 未注册用户
	// @gotags: json:"users"
	UnregisterUsers []*vo.SchoolUser `protobuf:"bytes,2,rep,name=unregisterUsers,proto3" json:"users"`
	// 已存在的用户
	// @gotags: json:"users"
	ExistUsers []*vo.SchoolUser `protobuf:"bytes,3,rep,name=existUsers,proto3" json:"users"`
}

func (x *AddRsp) Reset() {
	*x = AddRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_schooluser_add_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRsp) ProtoMessage() {}

func (x *AddRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_schooluser_add_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRsp.ProtoReflect.Descriptor instead.
func (*AddRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_schooluser_add_proto_rawDescGZIP(), []int{1}
}

func (x *AddRsp) GetUnregisterUsers() []*vo.SchoolUser {
	if x != nil {
		return x.UnregisterUsers
	}
	return nil
}

func (x *AddRsp) GetExistUsers() []*vo.SchoolUser {
	if x != nil {
		return x.ExistUsers
	}
	return nil
}

var File_relo_protocol_schooluser_add_proto protoreflect.FileDescriptor

var file_relo_protocol_schooluser_add_proto_rawDesc = []byte{
	0x0a, 0x22, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x61, 0x64, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x22,
	0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76, 0x6f,
	0x2f, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x2c, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x63,
	0x68, 0x6f, 0x6f, 0x6c, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x80, 0x01, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x65, 0x6c,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x6f, 0x2e, 0x53, 0x63,
	0x68, 0x6f, 0x6f, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12,
	0x42, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x26, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63,
	0x68, 0x6f, 0x6f, 0x6c, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x22, 0x8e, 0x01, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x52, 0x73, 0x70, 0x12, 0x46,
	0x0a, 0x0f, 0x75, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x6f, 0x2e, 0x53, 0x63, 0x68, 0x6f, 0x6f,
	0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0f, 0x75, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x3c, 0x0a, 0x0a, 0x65, 0x78, 0x69, 0x73, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x65, 0x6c,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x6f, 0x2e, 0x53, 0x63,
	0x68, 0x6f, 0x6f, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0a, 0x65, 0x78, 0x69, 0x73, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x75, 0x73, 0x65, 0x72,
	0x3b, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_relo_protocol_schooluser_add_proto_rawDescOnce sync.Once
	file_relo_protocol_schooluser_add_proto_rawDescData = file_relo_protocol_schooluser_add_proto_rawDesc
)

func file_relo_protocol_schooluser_add_proto_rawDescGZIP() []byte {
	file_relo_protocol_schooluser_add_proto_rawDescOnce.Do(func() {
		file_relo_protocol_schooluser_add_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_protocol_schooluser_add_proto_rawDescData)
	})
	return file_relo_protocol_schooluser_add_proto_rawDescData
}

var file_relo_protocol_schooluser_add_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_relo_protocol_schooluser_add_proto_goTypes = []interface{}{
	(*AddReq)(nil),                   // 0: relo.protocol.schooluser.AddReq
	(*AddRsp)(nil),                   // 1: relo.protocol.schooluser.AddRsp
	(*vo.SchoolUser)(nil),            // 2: relo.protocol.vo.SchoolUser
	(schooluser.RegistrationType)(0), // 3: relo.core.schooluser.RegistrationType
}
var file_relo_protocol_schooluser_add_proto_depIdxs = []int32{
	2, // 0: relo.protocol.schooluser.AddReq.users:type_name -> relo.protocol.vo.SchoolUser
	3, // 1: relo.protocol.schooluser.AddReq.register:type_name -> relo.core.schooluser.RegistrationType
	2, // 2: relo.protocol.schooluser.AddRsp.unregisterUsers:type_name -> relo.protocol.vo.SchoolUser
	2, // 3: relo.protocol.schooluser.AddRsp.existUsers:type_name -> relo.protocol.vo.SchoolUser
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_relo_protocol_schooluser_add_proto_init() }
func file_relo_protocol_schooluser_add_proto_init() {
	if File_relo_protocol_schooluser_add_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relo_protocol_schooluser_add_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_schooluser_add_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_protocol_schooluser_add_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_protocol_schooluser_add_proto_goTypes,
		DependencyIndexes: file_relo_protocol_schooluser_add_proto_depIdxs,
		MessageInfos:      file_relo_protocol_schooluser_add_proto_msgTypes,
	}.Build()
	File_relo_protocol_schooluser_add_proto = out.File
	file_relo_protocol_schooluser_add_proto_rawDesc = nil
	file_relo_protocol_schooluser_add_proto_goTypes = nil
	file_relo_protocol_schooluser_add_proto_depIdxs = nil
}
