// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/protocol/cloudfile/upload.proto

package cloudfile

import (
	cloudfile "github.com/reloclass/core/cloudfile"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文件上传请求
type UploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 文件编号
	// @gotags: query:"fileId" json:"fileId" validate:"omitempty,len=20"
	FileId string `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"fileId" query:"fileId" validate:"omitempty,len=20"`
	// 文件名字
	// @gotags:  query:"filename" json:"filename:" validate:"omitempty,without_special_symbol,filename"
	FileName string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"filename:" query:"filename" validate:"omitempty,without_special_symbol,filename"`
	// 文件大小
	// @gotags: query:"dataSize" json:"dataSize" validate:"required"
	DataSize int64 `protobuf:"varint,4,opt,name=data_size,json=dataSize,proto3" json:"dataSize" query:"dataSize" validate:"required"`
	// 文件上传类型
	// @gotags: query:"dirType" json:"dirType" validate:"required,oneof=system resource public private"
	DirType string `protobuf:"bytes,5,opt,name=dir_type,json=dirType,proto3" json:"dirType" query:"dirType" validate:"required,oneof=system resource public private"`
	// 学校编号
	// @gotags: query:"schoolId" json:"schoolId" validate:"omitempty"
	SchoolId int64 `protobuf:"varint,6,opt,name=school_id,json=schoolId,proto3" json:"schoolId" query:"schoolId" validate:"omitempty"`
	// 上传用户id
	// @gotags: query:"creatorId" json:"creatorId" validate:"omitempty"
	CreatorId int64 `protobuf:"varint,7,opt,name=creator_id,json=creatorId,proto3" json:"creatorId" query:"creatorId" validate:"omitempty"`
}

func (x *UploadReq) Reset() {
	*x = UploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_cloudfile_upload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReq) ProtoMessage() {}

func (x *UploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_cloudfile_upload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReq.ProtoReflect.Descriptor instead.
func (*UploadReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_cloudfile_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadReq) GetDataSize() int64 {
	if x != nil {
		return x.DataSize
	}
	return 0
}

func (x *UploadReq) GetDirType() string {
	if x != nil {
		return x.DirType
	}
	return ""
}

func (x *UploadReq) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *UploadReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

// 文件上传响应
type UploadRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 文件编号
	// @gotags: json:"fileId"
	FileId string `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"fileId"`
	// 上传地址
	// @gotags: json:"url"
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url"`
	// 云盘状态
	// @gotags: json:"state"
	State cloudfile.StorageState `protobuf:"varint,4,opt,name=state,proto3,enum=relo.core.cloudfile.StorageState" json:"state"`
}

func (x *UploadRsp) Reset() {
	*x = UploadRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_cloudfile_upload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRsp) ProtoMessage() {}

func (x *UploadRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_cloudfile_upload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRsp.ProtoReflect.Descriptor instead.
func (*UploadRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_cloudfile_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadRsp) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadRsp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadRsp) GetState() cloudfile.StorageState {
	if x != nil {
		return x.State
	}
	return cloudfile.StorageState_ENOUGH
}

// 完成上传请求
type CompleteUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 文件编号
	// @gotags: param:"fileId" json:"fileId"
	FileId string `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"fileId" param:"fileId"`
}

func (x *CompleteUploadReq) Reset() {
	*x = CompleteUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_cloudfile_upload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadReq) ProtoMessage() {}

func (x *CompleteUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_cloudfile_upload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadReq.ProtoReflect.Descriptor instead.
func (*CompleteUploadReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_cloudfile_upload_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteUploadReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

var File_relo_protocol_cloudfile_upload_proto protoreflect.FileDescriptor

var file_relo_protocol_cloudfile_upload_proto_rawDesc = []byte{
	0x0a, 0x24, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x69, 0x6c, 0x65, 0x1a,
	0x27, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x66, 0x69, 0x6c, 0x65, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb5, 0x01, 0x0a, 0x09, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x69, 0x72,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x69, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64,
	0x22, 0x6f, 0x0a, 0x09, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x73, 0x70, 0x12, 0x17, 0x0a,
	0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x37, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x22, 0x2c, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x42,
	0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65,
	0x6c, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x69, 0x6c, 0x65, 0x3b, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x66, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_protocol_cloudfile_upload_proto_rawDescOnce sync.Once
	file_relo_protocol_cloudfile_upload_proto_rawDescData = file_relo_protocol_cloudfile_upload_proto_rawDesc
)

func file_relo_protocol_cloudfile_upload_proto_rawDescGZIP() []byte {
	file_relo_protocol_cloudfile_upload_proto_rawDescOnce.Do(func() {
		file_relo_protocol_cloudfile_upload_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_protocol_cloudfile_upload_proto_rawDescData)
	})
	return file_relo_protocol_cloudfile_upload_proto_rawDescData
}

var file_relo_protocol_cloudfile_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_relo_protocol_cloudfile_upload_proto_goTypes = []interface{}{
	(*UploadReq)(nil),           // 0: relo.protocol.cloudfile.UploadReq
	(*UploadRsp)(nil),           // 1: relo.protocol.cloudfile.UploadRsp
	(*CompleteUploadReq)(nil),   // 2: relo.protocol.cloudfile.CompleteUploadReq
	(cloudfile.StorageState)(0), // 3: relo.core.cloudfile.StorageState
}
var file_relo_protocol_cloudfile_upload_proto_depIdxs = []int32{
	3, // 0: relo.protocol.cloudfile.UploadRsp.state:type_name -> relo.core.cloudfile.StorageState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_relo_protocol_cloudfile_upload_proto_init() }
func file_relo_protocol_cloudfile_upload_proto_init() {
	if File_relo_protocol_cloudfile_upload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relo_protocol_cloudfile_upload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_cloudfile_upload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_cloudfile_upload_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_protocol_cloudfile_upload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_protocol_cloudfile_upload_proto_goTypes,
		DependencyIndexes: file_relo_protocol_cloudfile_upload_proto_depIdxs,
		MessageInfos:      file_relo_protocol_cloudfile_upload_proto_msgTypes,
	}.Build()
	File_relo_protocol_cloudfile_upload_proto = out.File
	file_relo_protocol_cloudfile_upload_proto_rawDesc = nil
	file_relo_protocol_cloudfile_upload_proto_goTypes = nil
	file_relo_protocol_cloudfile_upload_proto_depIdxs = nil
}
