// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/protocol/asset/preview.proto

package asset

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取预览链接请求
type GetPreviewUrlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 学校编号
	// @gotags: json:"schoolId"
	SchoolId int64 `protobuf:"varint,2,opt,name=school_id,json=schoolId,proto3" json:"schoolId"`
	// 文件编号
	// @gotags: json:"fileId"
	FileId string `protobuf:"bytes,3,opt,name=file_id,json=fileId,proto3" json:"fileId"`
	// 文件名
	// @gotags: json:"fileName"
	FileName string `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"fileName"`
	// 文件类型
	// @gotags: json:"dirType"
	DirType string `protobuf:"bytes,5,opt,name=dir_type,json=dirType,proto3" json:"dirType"`
	// 用户id
	// @gotags: json:"userId"
	UserId int64 `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"userId"`
}

func (x *GetPreviewUrlReq) Reset() {
	*x = GetPreviewUrlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_asset_preview_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPreviewUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreviewUrlReq) ProtoMessage() {}

func (x *GetPreviewUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_asset_preview_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreviewUrlReq.ProtoReflect.Descriptor instead.
func (*GetPreviewUrlReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_asset_preview_proto_rawDescGZIP(), []int{0}
}

func (x *GetPreviewUrlReq) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *GetPreviewUrlReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetPreviewUrlReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetPreviewUrlReq) GetDirType() string {
	if x != nil {
		return x.DirType
	}
	return ""
}

func (x *GetPreviewUrlReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取预览链接响应
type GetPreviewUrlRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 文件预览链接
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetPreviewUrlRsp) Reset() {
	*x = GetPreviewUrlRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_asset_preview_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPreviewUrlRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreviewUrlRsp) ProtoMessage() {}

func (x *GetPreviewUrlRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_asset_preview_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreviewUrlRsp.ProtoReflect.Descriptor instead.
func (*GetPreviewUrlRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_asset_preview_proto_rawDescGZIP(), []int{1}
}

func (x *GetPreviewUrlRsp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_relo_protocol_asset_preview_proto protoreflect.FileDescriptor

var file_relo_protocol_asset_preview_proto_rawDesc = []byte{
	0x0a, 0x21, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x22, 0x99, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x64, 0x69, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x64, 0x69, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x55, 0x72, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x3b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_protocol_asset_preview_proto_rawDescOnce sync.Once
	file_relo_protocol_asset_preview_proto_rawDescData = file_relo_protocol_asset_preview_proto_rawDesc
)

func file_relo_protocol_asset_preview_proto_rawDescGZIP() []byte {
	file_relo_protocol_asset_preview_proto_rawDescOnce.Do(func() {
		file_relo_protocol_asset_preview_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_protocol_asset_preview_proto_rawDescData)
	})
	return file_relo_protocol_asset_preview_proto_rawDescData
}

var file_relo_protocol_asset_preview_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_relo_protocol_asset_preview_proto_goTypes = []interface{}{
	(*GetPreviewUrlReq)(nil), // 0: relo.protocol.asset.GetPreviewUrlReq
	(*GetPreviewUrlRsp)(nil), // 1: relo.protocol.asset.GetPreviewUrlRsp
}
var file_relo_protocol_asset_preview_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relo_protocol_asset_preview_proto_init() }
func file_relo_protocol_asset_preview_proto_init() {
	if File_relo_protocol_asset_preview_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relo_protocol_asset_preview_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPreviewUrlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_asset_preview_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPreviewUrlRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_protocol_asset_preview_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_protocol_asset_preview_proto_goTypes,
		DependencyIndexes: file_relo_protocol_asset_preview_proto_depIdxs,
		MessageInfos:      file_relo_protocol_asset_preview_proto_msgTypes,
	}.Build()
	File_relo_protocol_asset_preview_proto = out.File
	file_relo_protocol_asset_preview_proto_rawDesc = nil
	file_relo_protocol_asset_preview_proto_goTypes = nil
	file_relo_protocol_asset_preview_proto_depIdxs = nil
}
