// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/protocol/filechunk/init.proto

package filechunk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 初始化分块上传请求
type InitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 文件编号
	// @gotags: json:"fileId" validate:"required,len=20"
	FileId string `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"fileId" validate:"required,len=20"`
	// 文件所属类型
	// @gotags: json:"type" validate:"required,oneof=course public private resource"
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type" validate:"required,oneof=course public private resource"`
	// 学校编号
	// @gotags: json:"schoolId,string" validate:"omitempty"
	SchoolId int64 `protobuf:"varint,4,opt,name=school_id,json=schoolId,proto3" json:"schoolId,string" validate:"omitempty"`
	// 上传内容的contentType
	// @gotags: json:"contentType" validate:"required"
	ContentType string `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"contentType" validate:"required"`
}

func (x *InitReq) Reset() {
	*x = InitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_filechunk_init_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitReq) ProtoMessage() {}

func (x *InitReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_filechunk_init_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitReq.ProtoReflect.Descriptor instead.
func (*InitReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_filechunk_init_proto_rawDescGZIP(), []int{0}
}

func (x *InitReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *InitReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InitReq) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *InitReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// 初始化分块上传响应
type InitRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 腾讯Cos对象存储分块上传时唯一标识Id
	// @gotags: json:"uploadId"
	UploadId string `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"uploadId"`
}

func (x *InitRsp) Reset() {
	*x = InitRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_filechunk_init_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRsp) ProtoMessage() {}

func (x *InitRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_filechunk_init_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRsp.ProtoReflect.Descriptor instead.
func (*InitRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_filechunk_init_proto_rawDescGZIP(), []int{1}
}

func (x *InitRsp) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

var File_relo_protocol_filechunk_init_proto protoreflect.FileDescriptor

var file_relo_protocol_filechunk_init_proto_rawDesc = []byte{
	0x0a, 0x22, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x66, 0x69, 0x6c, 0x65, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2f, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x76, 0x0a,
	0x07, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x26, 0x0a, 0x07, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x73, 0x70,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x42, 0x33, 0x5a,
	0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x66,
	0x69, 0x6c, 0x65, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x3b, 0x66, 0x69, 0x6c, 0x65, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_protocol_filechunk_init_proto_rawDescOnce sync.Once
	file_relo_protocol_filechunk_init_proto_rawDescData = file_relo_protocol_filechunk_init_proto_rawDesc
)

func file_relo_protocol_filechunk_init_proto_rawDescGZIP() []byte {
	file_relo_protocol_filechunk_init_proto_rawDescOnce.Do(func() {
		file_relo_protocol_filechunk_init_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_protocol_filechunk_init_proto_rawDescData)
	})
	return file_relo_protocol_filechunk_init_proto_rawDescData
}

var file_relo_protocol_filechunk_init_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_relo_protocol_filechunk_init_proto_goTypes = []interface{}{
	(*InitReq)(nil), // 0: relo.protocol.cloudfile.InitReq
	(*InitRsp)(nil), // 1: relo.protocol.cloudfile.InitRsp
}
var file_relo_protocol_filechunk_init_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relo_protocol_filechunk_init_proto_init() }
func file_relo_protocol_filechunk_init_proto_init() {
	if File_relo_protocol_filechunk_init_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relo_protocol_filechunk_init_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_filechunk_init_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_protocol_filechunk_init_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_protocol_filechunk_init_proto_goTypes,
		DependencyIndexes: file_relo_protocol_filechunk_init_proto_depIdxs,
		MessageInfos:      file_relo_protocol_filechunk_init_proto_msgTypes,
	}.Build()
	File_relo_protocol_filechunk_init_proto = out.File
	file_relo_protocol_filechunk_init_proto_rawDesc = nil
	file_relo_protocol_filechunk_init_proto_goTypes = nil
	file_relo_protocol_filechunk_init_proto_depIdxs = nil
}
