// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/protocol/filechunk/multipart_upload.proto

package filechunk

import (
	cloudfile "github.com/reloclass/core/cloudfile"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 初始化分块上传请求
type InitMultipartUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 文件编号
	// @gotags: json:"fileId" validate:"required,len=20"
	FileId string `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"fileId" validate:"required,len=20"`
	// 文件所属类型
	// @gotags: json:"type" validate:"required,oneof=course public private resource"
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type" validate:"required,oneof=course public private resource"`
	// 学校编号
	// @gotags: json:"schoolId,string" validate:"omitempty"
	SchoolId int64 `protobuf:"varint,4,opt,name=school_id,json=schoolId,proto3" json:"schoolId,string" validate:"omitempty"`
	// 上传内容的contentType
	// @gotags: json:"contentType" validate:"required"
	ContentType string `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"contentType" validate:"required"`
}

func (x *InitMultipartUploadReq) Reset() {
	*x = InitMultipartUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_filechunk_multipart_upload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitMultipartUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitMultipartUploadReq) ProtoMessage() {}

func (x *InitMultipartUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_filechunk_multipart_upload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitMultipartUploadReq.ProtoReflect.Descriptor instead.
func (*InitMultipartUploadReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_filechunk_multipart_upload_proto_rawDescGZIP(), []int{0}
}

func (x *InitMultipartUploadReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *InitMultipartUploadReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InitMultipartUploadReq) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *InitMultipartUploadReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// 初始化分块上传响应
type InitMultipartUploadRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 腾讯Cos对象存储分块上传时唯一标识Id
	// @gotags: json:"uploadId"
	UploadId string `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"uploadId"`
}

func (x *InitMultipartUploadRsp) Reset() {
	*x = InitMultipartUploadRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_filechunk_multipart_upload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitMultipartUploadRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitMultipartUploadRsp) ProtoMessage() {}

func (x *InitMultipartUploadRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_filechunk_multipart_upload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitMultipartUploadRsp.ProtoReflect.Descriptor instead.
func (*InitMultipartUploadRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_filechunk_multipart_upload_proto_rawDescGZIP(), []int{1}
}

func (x *InitMultipartUploadRsp) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

// 完成分块上传请求
type CompleteMultipartUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 文件编号
	// @gotags: json:"fileId" validate:"required,len=20"
	FileId string `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"fileId" validate:"required,len=20"`
	// 腾讯Cos对象存储分块上传时唯一标识Id
	// @gotags: json:"uploadId" validate:"required"
	UploadId string `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"uploadId" validate:"required"`
	// 每一部分上传返回信息
	// @gotags: json:"parts" validate:"required,dive"
	Parts []*cloudfile.ChunkInfo `protobuf:"bytes,4,rep,name=parts,proto3" json:"parts" validate:"required,dive"`
}

func (x *CompleteMultipartUploadReq) Reset() {
	*x = CompleteMultipartUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_filechunk_multipart_upload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteMultipartUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMultipartUploadReq) ProtoMessage() {}

func (x *CompleteMultipartUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_filechunk_multipart_upload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMultipartUploadReq.ProtoReflect.Descriptor instead.
func (*CompleteMultipartUploadReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_filechunk_multipart_upload_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteMultipartUploadReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CompleteMultipartUploadReq) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CompleteMultipartUploadReq) GetParts() []*cloudfile.ChunkInfo {
	if x != nil {
		return x.Parts
	}
	return nil
}

// 中断分块上传请求
type AbortMultipartUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 文件编号
	// @gotags: json:"fileId" validate:"required,len=20"
	FileId string `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"fileId" validate:"required,len=20"`
}

func (x *AbortMultipartUploadReq) Reset() {
	*x = AbortMultipartUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_filechunk_multipart_upload_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbortMultipartUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortMultipartUploadReq) ProtoMessage() {}

func (x *AbortMultipartUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_filechunk_multipart_upload_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortMultipartUploadReq.ProtoReflect.Descriptor instead.
func (*AbortMultipartUploadReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_filechunk_multipart_upload_proto_rawDescGZIP(), []int{3}
}

func (x *AbortMultipartUploadReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

var File_relo_protocol_filechunk_multipart_upload_proto protoreflect.FileDescriptor

var file_relo_protocol_filechunk_multipart_upload_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x66, 0x69, 0x6c, 0x65, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x61, 0x72, 0x74, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x17, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x69, 0x6c, 0x65, 0x1a, 0x24, 0x72, 0x65, 0x6c, 0x6f, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x85, 0x01, 0x0a, 0x16, 0x49, 0x6e, 0x69, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72,
	0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x6f, 0x6f,
	0x6c, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x63, 0x68, 0x6f,
	0x6f, 0x6c, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x35, 0x0a, 0x16, 0x49, 0x6e, 0x69, 0x74, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x73,
	0x70, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x22, 0x88,
	0x01, 0x0a, 0x1a, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x22, 0x32, 0x0a, 0x17, 0x41, 0x62, 0x6f,
	0x72, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x42, 0x33, 0x5a,
	0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x66,
	0x69, 0x6c, 0x65, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x3b, 0x66, 0x69, 0x6c, 0x65, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_protocol_filechunk_multipart_upload_proto_rawDescOnce sync.Once
	file_relo_protocol_filechunk_multipart_upload_proto_rawDescData = file_relo_protocol_filechunk_multipart_upload_proto_rawDesc
)

func file_relo_protocol_filechunk_multipart_upload_proto_rawDescGZIP() []byte {
	file_relo_protocol_filechunk_multipart_upload_proto_rawDescOnce.Do(func() {
		file_relo_protocol_filechunk_multipart_upload_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_protocol_filechunk_multipart_upload_proto_rawDescData)
	})
	return file_relo_protocol_filechunk_multipart_upload_proto_rawDescData
}

var file_relo_protocol_filechunk_multipart_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_relo_protocol_filechunk_multipart_upload_proto_goTypes = []interface{}{
	(*InitMultipartUploadReq)(nil),     // 0: relo.protocol.cloudfile.InitMultipartUploadReq
	(*InitMultipartUploadRsp)(nil),     // 1: relo.protocol.cloudfile.InitMultipartUploadRsp
	(*CompleteMultipartUploadReq)(nil), // 2: relo.protocol.cloudfile.CompleteMultipartUploadReq
	(*AbortMultipartUploadReq)(nil),    // 3: relo.protocol.cloudfile.AbortMultipartUploadReq
	(*cloudfile.ChunkInfo)(nil),        // 4: relo.core.cloudfile.ChunkInfo
}
var file_relo_protocol_filechunk_multipart_upload_proto_depIdxs = []int32{
	4, // 0: relo.protocol.cloudfile.CompleteMultipartUploadReq.parts:type_name -> relo.core.cloudfile.ChunkInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_relo_protocol_filechunk_multipart_upload_proto_init() }
func file_relo_protocol_filechunk_multipart_upload_proto_init() {
	if File_relo_protocol_filechunk_multipart_upload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relo_protocol_filechunk_multipart_upload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitMultipartUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_filechunk_multipart_upload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitMultipartUploadRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_filechunk_multipart_upload_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteMultipartUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_filechunk_multipart_upload_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbortMultipartUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_protocol_filechunk_multipart_upload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_protocol_filechunk_multipart_upload_proto_goTypes,
		DependencyIndexes: file_relo_protocol_filechunk_multipart_upload_proto_depIdxs,
		MessageInfos:      file_relo_protocol_filechunk_multipart_upload_proto_msgTypes,
	}.Build()
	File_relo_protocol_filechunk_multipart_upload_proto = out.File
	file_relo_protocol_filechunk_multipart_upload_proto_rawDesc = nil
	file_relo_protocol_filechunk_multipart_upload_proto_goTypes = nil
	file_relo_protocol_filechunk_multipart_upload_proto_depIdxs = nil
}
