// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/protocol/disk/get.proto

package disk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取文件列表请求
type GetFilesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 编号
	// 当Type为private时 为用户编号
	// 当Type为public 时 为机构编号
	// @gotags: query:"id" validate:"required"`
	Id int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty" query:"id" validate:"required"`
	// 根据不同的编号获取不同的地址
	// private 个人云盘
	// public 公共云盘
	// @gotags: query:"type" validate:"required,oneof= public private"`
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty" query:"type" validate:"required,oneof= public private"`
	// 父路径
	// @gotags: query:"path" validate:"required,startswith=/,filename"`
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty" query:"path" validate:"required,startswith=/,filename"`
}

func (x *GetFilesReq) Reset() {
	*x = GetFilesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_disk_get_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesReq) ProtoMessage() {}

func (x *GetFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_disk_get_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesReq.ProtoReflect.Descriptor instead.
func (*GetFilesReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_disk_get_proto_rawDescGZIP(), []int{0}
}

func (x *GetFilesReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetFilesReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetFilesReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// 获取文件列表响应
type GetFilesRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 文件信息列表
	Infos []*DiskDirFile `protobuf:"bytes,2,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *GetFilesRsp) Reset() {
	*x = GetFilesRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_disk_get_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFilesRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesRsp) ProtoMessage() {}

func (x *GetFilesRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_disk_get_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesRsp.ProtoReflect.Descriptor instead.
func (*GetFilesRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_disk_get_proto_rawDescGZIP(), []int{1}
}

func (x *GetFilesRsp) GetInfos() []*DiskDirFile {
	if x != nil {
		return x.Infos
	}
	return nil
}

// 文件信息
type DiskDirFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 文件类型
	// 目录：1
	// 文件：2
	Type int32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	// Path 文件路径
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// 更新时间
	// @gotags: json:"updateTime"
	UpdateTime int64 `protobuf:"varint,4,opt,name=update_time,json=updateTime,proto3" json:"updateTime"`
}

func (x *DiskDirFile) Reset() {
	*x = DiskDirFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_disk_get_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiskDirFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskDirFile) ProtoMessage() {}

func (x *DiskDirFile) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_disk_get_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskDirFile.ProtoReflect.Descriptor instead.
func (*DiskDirFile) Descriptor() ([]byte, []int) {
	return file_relo_protocol_disk_get_proto_rawDescGZIP(), []int{2}
}

func (x *DiskDirFile) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DiskDirFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskDirFile) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// 磁盘信息請求
type GetDiskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 编号
	// 当Type为private时 为用户编号
	// 当Type为public 时 为机构编号
	// @gotags: query:"id" validate:"required"`
	Id int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty" query:"id" validate:"required"`
	// 根据不同的编号获取不同的地址
	// private 个人云盘
	// public 公共云盘
	// @gotags: query:"type" validate:"required,oneof= public private"`
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty" query:"type" validate:"required,oneof= public private"`
}

func (x *GetDiskReq) Reset() {
	*x = GetDiskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_disk_get_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDiskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskReq) ProtoMessage() {}

func (x *GetDiskReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_disk_get_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskReq.ProtoReflect.Descriptor instead.
func (*GetDiskReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_disk_get_proto_rawDescGZIP(), []int{3}
}

func (x *GetDiskReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDiskReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// 磁盘信息响应
type GetDiskRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 默认总大小 单位B
	// @gotags: json:"defaultSize"
	DefaultSize int64 `protobuf:"varint,2,opt,name=default_size,json=defaultSize,proto3" json:"defaultSize"`
	// 使用大小 单位B
	// @gotags: json:"useSize"
	UseSize int64 `protobuf:"varint,3,opt,name=use_size,json=useSize,proto3" json:"useSize"`
}

func (x *GetDiskRsp) Reset() {
	*x = GetDiskRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_disk_get_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDiskRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskRsp) ProtoMessage() {}

func (x *GetDiskRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_disk_get_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskRsp.ProtoReflect.Descriptor instead.
func (*GetDiskRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_disk_get_proto_rawDescGZIP(), []int{4}
}

func (x *GetDiskRsp) GetDefaultSize() int64 {
	if x != nil {
		return x.DefaultSize
	}
	return 0
}

func (x *GetDiskRsp) GetUseSize() int64 {
	if x != nil {
		return x.UseSize
	}
	return 0
}

var File_relo_protocol_disk_get_proto protoreflect.FileDescriptor

var file_relo_protocol_disk_get_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x64, 0x69, 0x73, 0x6b, 0x2f, 0x67, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x64, 0x69,
	0x73, 0x6b, 0x22, 0x45, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x44, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x64, 0x69, 0x73, 0x6b, 0x2e, 0x44, 0x69, 0x73,
	0x6b, 0x44, 0x69, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22,
	0x56, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x6b, 0x44, 0x69, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x44, 0x69,
	0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x4a, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x44, 0x69, 0x73, 0x6b, 0x52, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x75, 0x73,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x64, 0x69, 0x73, 0x6b, 0x3b, 0x64, 0x69, 0x73, 0x6b,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_protocol_disk_get_proto_rawDescOnce sync.Once
	file_relo_protocol_disk_get_proto_rawDescData = file_relo_protocol_disk_get_proto_rawDesc
)

func file_relo_protocol_disk_get_proto_rawDescGZIP() []byte {
	file_relo_protocol_disk_get_proto_rawDescOnce.Do(func() {
		file_relo_protocol_disk_get_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_protocol_disk_get_proto_rawDescData)
	})
	return file_relo_protocol_disk_get_proto_rawDescData
}

var file_relo_protocol_disk_get_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_relo_protocol_disk_get_proto_goTypes = []interface{}{
	(*GetFilesReq)(nil), // 0: relo.protocol.disk.GetFilesReq
	(*GetFilesRsp)(nil), // 1: relo.protocol.disk.GetFilesRsp
	(*DiskDirFile)(nil), // 2: relo.protocol.disk.DiskDirFile
	(*GetDiskReq)(nil),  // 3: relo.protocol.disk.GetDiskReq
	(*GetDiskRsp)(nil),  // 4: relo.protocol.disk.GetDiskRsp
}
var file_relo_protocol_disk_get_proto_depIdxs = []int32{
	2, // 0: relo.protocol.disk.GetFilesRsp.infos:type_name -> relo.protocol.disk.DiskDirFile
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_relo_protocol_disk_get_proto_init() }
func file_relo_protocol_disk_get_proto_init() {
	if File_relo_protocol_disk_get_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relo_protocol_disk_get_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFilesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_disk_get_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFilesRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_disk_get_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiskDirFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_disk_get_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDiskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_disk_get_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDiskRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_protocol_disk_get_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_protocol_disk_get_proto_goTypes,
		DependencyIndexes: file_relo_protocol_disk_get_proto_depIdxs,
		MessageInfos:      file_relo_protocol_disk_get_proto_msgTypes,
	}.Build()
	File_relo_protocol_disk_get_proto = out.File
	file_relo_protocol_disk_get_proto_rawDesc = nil
	file_relo_protocol_disk_get_proto_goTypes = nil
	file_relo_protocol_disk_get_proto_depIdxs = nil
}
