// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/protocol/lesson/get.proto

package lesson

import (
	course "github.com/reloclass/core/course"
	lesson "github.com/reloclass/core/lesson"
	vo "github.com/reloclass/protocol/vo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分页获取有课节安排的日期请求
type GetsDaysReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// StartTime 开始时间条件
	// @gotags: query:"startTime" json:"startTime" validate:"required"
	StartTime string `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"startTime" query:"startTime" validate:"required"`
	// EndTime 结束时间条件
	// @gotags: query:"endTime" json:"endTime" validate:"required"
	EndTime string `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"endTime" query:"endTime" validate:"required"`
	// 要查用户的编号
	// @gotags: query:"userId" json:"userId,string" validate:"required"
	UserId int64 `protobuf:"varint,8,opt,name=user_id,json=userId,proto3" json:"userId,string" query:"userId" validate:"required"`
}

func (x *GetsDaysReq) Reset() {
	*x = GetsDaysReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_lesson_get_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsDaysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsDaysReq) ProtoMessage() {}

func (x *GetsDaysReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_lesson_get_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsDaysReq.ProtoReflect.Descriptor instead.
func (*GetsDaysReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_lesson_get_proto_rawDescGZIP(), []int{0}
}

func (x *GetsDaysReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetsDaysReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetsDaysReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 分页获取有课节安排的日期响应
type GetsDaysRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 日期
	Dates []string `protobuf:"bytes,2,rep,name=dates,proto3" json:"dates,omitempty"`
}

func (x *GetsDaysRsp) Reset() {
	*x = GetsDaysRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_lesson_get_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsDaysRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsDaysRsp) ProtoMessage() {}

func (x *GetsDaysRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_lesson_get_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsDaysRsp.ProtoReflect.Descriptor instead.
func (*GetsDaysRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_lesson_get_proto_rawDescGZIP(), []int{1}
}

func (x *GetsDaysRsp) GetDates() []string {
	if x != nil {
		return x.Dates
	}
	return nil
}

// 获取课节请求
type GetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 课节编号
	// @gotags: param:"id"
	Id int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty" param:"id"`
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_lesson_get_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_lesson_get_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_lesson_get_proto_rawDescGZIP(), []int{2}
}

func (x *GetReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 分页获取课节信息请求
type GetsByPagingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 当前页
	// @gotags: default:"1" query:"page"
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty" default:"1" query:"page"`
	// 每页大小
	// @gotags: default:"20" query:"perPage"
	Size int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty" default:"20" query:"perPage"`
	// 查询关键字
	// @gotags: query:"keyword"
	Keyword string `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty" query:"keyword"`
	// 排序规则
	// @gotags: default:"desc" query:"sortOrder" validate:"oneof=desc DESC asc ASC"
	Order string `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty" default:"desc" query:"sortOrder" validate:"oneof=desc DESC asc ASC"`
	// 排序字段
	// @gotags: default:"created_at" query:"sortField" validate:"oneof=updated_at created_at"
	Sort string `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty" default:"created_at" query:"sortField" validate:"oneof=updated_at created_at"`
	// 课程编号
	// @gotags: query:"courseId" json:"courseId,string"
	CourseId int64 `protobuf:"varint,7,opt,name=course_id,json=courseId,proto3" json:"courseId,string" query:"courseId"`
	// 主讲老师
	// @gotags: query:"teacherKey" json:"teacherKey"
	TeacherKey string `protobuf:"bytes,8,opt,name=teacher_key,json=teacherKey,proto3" json:"teacherKey" query:"teacherKey"`
	// 助教
	// @gotags: query:"assistantKey" json:"assistantKey"
	AssistantKey string `protobuf:"bytes,9,opt,name=assistant_key,json=assistantKey,proto3" json:"assistantKey" query:"assistantKey"`
	// 课节名称
	// @gotags: query:"nameKey" json:"nameKey"
	NameKey string `protobuf:"bytes,10,opt,name=name_key,json=nameKey,proto3" json:"nameKey" query:"nameKey"`
	// 开始时间条件
	// @gotags: query:"startTime" json:"startTime"
	StartTime string `protobuf:"bytes,11,opt,name=start_time,json=startTime,proto3" json:"startTime" query:"startTime"`
	// 结束时间条件
	// @gotags: query:"endTime" json:"endTime"
	EndTime string `protobuf:"bytes,12,opt,name=end_time,json=endTime,proto3" json:"endTime" query:"endTime"`
	// 学校编号
	// @gotags: query:"schoolId" json:"schoolId"
	SchoolId int64 `protobuf:"varint,13,opt,name=school_id,json=schoolId,proto3" json:"schoolId" query:"schoolId"`
	// 课程状态
	// @gotags: query:"statuses" json:"statuses"
	Statuses []lesson.Status `protobuf:"varint,14,rep,packed,name=statuses,proto3,enum=relo.core.lesson.Status" json:"statuses" query:"statuses"`
	// 上课模式
	// @gotags: query: "classMode" json:"classMode" validate:"omitempty,oneof=1 2 3"
	ClassMode course.ClassMode `protobuf:"varint,15,opt,name=class_mode,json=classMode,proto3,enum=relo.core.course.ClassMode" json:"classMode" validate:"omitempty,oneof=1 2 3"`
	// 课程类型
	// @gotags: query:"type"
	Type course.Type `protobuf:"varint,16,opt,name=type,proto3,enum=relo.core.course.Type" json:"type,omitempty" query:"type"`
}

func (x *GetsByPagingReq) Reset() {
	*x = GetsByPagingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_lesson_get_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsByPagingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsByPagingReq) ProtoMessage() {}

func (x *GetsByPagingReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_lesson_get_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsByPagingReq.ProtoReflect.Descriptor instead.
func (*GetsByPagingReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_lesson_get_proto_rawDescGZIP(), []int{3}
}

func (x *GetsByPagingReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetsByPagingReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetsByPagingReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetsByPagingReq) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *GetsByPagingReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetsByPagingReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *GetsByPagingReq) GetTeacherKey() string {
	if x != nil {
		return x.TeacherKey
	}
	return ""
}

func (x *GetsByPagingReq) GetAssistantKey() string {
	if x != nil {
		return x.AssistantKey
	}
	return ""
}

func (x *GetsByPagingReq) GetNameKey() string {
	if x != nil {
		return x.NameKey
	}
	return ""
}

func (x *GetsByPagingReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetsByPagingReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetsByPagingReq) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *GetsByPagingReq) GetStatuses() []lesson.Status {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *GetsByPagingReq) GetClassMode() course.ClassMode {
	if x != nil {
		return x.ClassMode
	}
	return course.ClassMode_CLASS_MODE_UNSPECIFIED
}

func (x *GetsByPagingReq) GetType() course.Type {
	if x != nil {
		return x.Type
	}
	return course.Type_COURSE_TYPE_UNSPECIFIED
}

// 分页获取课节信息响应
type GetsByPagingRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 总数
	// @gotags: json:"totalNum"
	TotalNum int64 `protobuf:"varint,2,opt,name=total_num,json=totalNum,proto3" json:"totalNum"`
	// 数据
	Items []*vo.EsLesson `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetsByPagingRsp) Reset() {
	*x = GetsByPagingRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_lesson_get_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsByPagingRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsByPagingRsp) ProtoMessage() {}

func (x *GetsByPagingRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_lesson_get_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsByPagingRsp.ProtoReflect.Descriptor instead.
func (*GetsByPagingRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_lesson_get_proto_rawDescGZIP(), []int{4}
}

func (x *GetsByPagingRsp) GetTotalNum() int64 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

func (x *GetsByPagingRsp) GetItems() []*vo.EsLesson {
	if x != nil {
		return x.Items
	}
	return nil
}

// 获取课节总数请求
type GetCountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 课程编号
	// @gotags: query:"courseId" json:"courseId,string"
	CourseId int64 `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"courseId,string" query:"courseId"`
	// 学校编号
	// @gotags: query:"schoolId" json:"schoolId,string"
	SchoolId int64 `protobuf:"varint,3,opt,name=school_id,json=schoolId,proto3" json:"schoolId,string" query:"schoolId"`
}

func (x *GetCountReq) Reset() {
	*x = GetCountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_lesson_get_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountReq) ProtoMessage() {}

func (x *GetCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_lesson_get_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountReq.ProtoReflect.Descriptor instead.
func (*GetCountReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_lesson_get_proto_rawDescGZIP(), []int{5}
}

func (x *GetCountReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *GetCountReq) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

// 分页获取课节信息请求
type GetsByCurrentPagingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 当前页
	// @gotags: default:"1" query:"page"
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty" default:"1" query:"page"`
	// 每页大小
	// @gotags: default:"20" query:"perPage"
	Size int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty" default:"20" query:"perPage"`
	// 查询关键字
	// @gotags: query:"keyword"
	Keyword string `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty" query:"keyword"`
	// 排序规则
	// @gotags: default:"desc" query:"sortOrder" validate:"oneof=desc DESC asc ASC"
	Order string `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty" default:"desc" query:"sortOrder" validate:"oneof=desc DESC asc ASC"`
	// 排序字段
	// @gotags: default:"created_at" query:"sortField" validate:"oneof=updated_at created_at"
	Sort string `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty" default:"created_at" query:"sortField" validate:"oneof=updated_at created_at"`
	// @gotags: param:"date"
	Date string `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty" param:"date"`
}

func (x *GetsByCurrentPagingReq) Reset() {
	*x = GetsByCurrentPagingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_lesson_get_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsByCurrentPagingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsByCurrentPagingReq) ProtoMessage() {}

func (x *GetsByCurrentPagingReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_lesson_get_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsByCurrentPagingReq.ProtoReflect.Descriptor instead.
func (*GetsByCurrentPagingReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_lesson_get_proto_rawDescGZIP(), []int{6}
}

func (x *GetsByCurrentPagingReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetsByCurrentPagingReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetsByCurrentPagingReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetsByCurrentPagingReq) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *GetsByCurrentPagingReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetsByCurrentPagingReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// 分页获取课节信息响应
type GetsByCurrentPagingRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 总数
	// @gotags: json:"totalNum"
	TotalNum int64 `protobuf:"varint,2,opt,name=total_num,json=totalNum,proto3" json:"totalNum"`
	// 数据
	Items []*vo.EsLesson `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetsByCurrentPagingRsp) Reset() {
	*x = GetsByCurrentPagingRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_lesson_get_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsByCurrentPagingRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsByCurrentPagingRsp) ProtoMessage() {}

func (x *GetsByCurrentPagingRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_lesson_get_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsByCurrentPagingRsp.ProtoReflect.Descriptor instead.
func (*GetsByCurrentPagingRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_lesson_get_proto_rawDescGZIP(), []int{7}
}

func (x *GetsByCurrentPagingRsp) GetTotalNum() int64 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

func (x *GetsByCurrentPagingRsp) GetItems() []*vo.EsLesson {
	if x != nil {
		return x.Items
	}
	return nil
}

// 获取课节状态请求
type GetsStatuesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 课节编号
	// @gotags: query:"ids" validate:"min=1"
	Ids []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty" query:"ids" validate:"min=1"`
}

func (x *GetsStatuesReq) Reset() {
	*x = GetsStatuesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_lesson_get_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsStatuesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsStatuesReq) ProtoMessage() {}

func (x *GetsStatuesReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_lesson_get_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsStatuesReq.ProtoReflect.Descriptor instead.
func (*GetsStatuesReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_lesson_get_proto_rawDescGZIP(), []int{8}
}

func (x *GetsStatuesReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_relo_protocol_lesson_get_proto protoreflect.FileDescriptor

var file_relo_protocol_lesson_get_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x2f, 0x67, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x14, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x1a, 0x20, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76, 0x6f, 0x2f, 0x65, 0x73, 0x5f, 0x6c, 0x65, 0x73, 0x73,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x72, 0x65, 0x6c, 0x6f,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x73, 0x44,
	0x61, 0x79, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x73, 0x44, 0x61, 0x79, 0x73, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x74, 0x65, 0x73, 0x22, 0x18,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xf0, 0x03, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x73, 0x42, 0x79, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x61, 0x63,
	0x68, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74,
	0x61, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61,
	0x73, 0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x6e,
	0x61, 0x6d, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e,
	0x61, 0x6d, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x34, 0x0a,
	0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0e, 0x32,
	0x18, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6c, 0x65, 0x73, 0x73,
	0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x4d, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4d, 0x6f, 0x64, 0x65, 0x12,
	0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x60, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x73, 0x42, 0x79, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x73, 0x70, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x30, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65, 0x6c,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x6f, 0x2e, 0x45, 0x73,
	0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x47, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x63, 0x68,
	0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x63,
	0x68, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x22, 0x98, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x73, 0x42,
	0x79, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x22, 0x67, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x73, 0x42, 0x79, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x30, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x6f, 0x2e, 0x45, 0x73, 0x4c, 0x65, 0x73,
	0x73, 0x6f, 0x6e, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x22, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x42, 0x2d,
	0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c,
	0x6f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x3b, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_protocol_lesson_get_proto_rawDescOnce sync.Once
	file_relo_protocol_lesson_get_proto_rawDescData = file_relo_protocol_lesson_get_proto_rawDesc
)

func file_relo_protocol_lesson_get_proto_rawDescGZIP() []byte {
	file_relo_protocol_lesson_get_proto_rawDescOnce.Do(func() {
		file_relo_protocol_lesson_get_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_protocol_lesson_get_proto_rawDescData)
	})
	return file_relo_protocol_lesson_get_proto_rawDescData
}

var file_relo_protocol_lesson_get_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_relo_protocol_lesson_get_proto_goTypes = []interface{}{
	(*GetsDaysReq)(nil),            // 0: relo.protocol.lesson.GetsDaysReq
	(*GetsDaysRsp)(nil),            // 1: relo.protocol.lesson.GetsDaysRsp
	(*GetReq)(nil),                 // 2: relo.protocol.lesson.GetReq
	(*GetsByPagingReq)(nil),        // 3: relo.protocol.lesson.GetsByPagingReq
	(*GetsByPagingRsp)(nil),        // 4: relo.protocol.lesson.GetsByPagingRsp
	(*GetCountReq)(nil),            // 5: relo.protocol.lesson.GetCountReq
	(*GetsByCurrentPagingReq)(nil), // 6: relo.protocol.lesson.GetsByCurrentPagingReq
	(*GetsByCurrentPagingRsp)(nil), // 7: relo.protocol.lesson.GetsByCurrentPagingRsp
	(*GetsStatuesReq)(nil),         // 8: relo.protocol.lesson.GetsStatuesReq
	(lesson.Status)(0),             // 9: relo.core.lesson.Status
	(course.ClassMode)(0),          // 10: relo.core.course.ClassMode
	(course.Type)(0),               // 11: relo.core.course.Type
	(*vo.EsLesson)(nil),            // 12: relo.protocol.vo.EsLesson
}
var file_relo_protocol_lesson_get_proto_depIdxs = []int32{
	9,  // 0: relo.protocol.lesson.GetsByPagingReq.statuses:type_name -> relo.core.lesson.Status
	10, // 1: relo.protocol.lesson.GetsByPagingReq.class_mode:type_name -> relo.core.course.ClassMode
	11, // 2: relo.protocol.lesson.GetsByPagingReq.type:type_name -> relo.core.course.Type
	12, // 3: relo.protocol.lesson.GetsByPagingRsp.items:type_name -> relo.protocol.vo.EsLesson
	12, // 4: relo.protocol.lesson.GetsByCurrentPagingRsp.items:type_name -> relo.protocol.vo.EsLesson
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_relo_protocol_lesson_get_proto_init() }
func file_relo_protocol_lesson_get_proto_init() {
	if File_relo_protocol_lesson_get_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relo_protocol_lesson_get_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsDaysReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_lesson_get_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsDaysRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_lesson_get_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_lesson_get_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsByPagingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_lesson_get_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsByPagingRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_lesson_get_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_lesson_get_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsByCurrentPagingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_lesson_get_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsByCurrentPagingRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_lesson_get_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsStatuesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_protocol_lesson_get_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_protocol_lesson_get_proto_goTypes,
		DependencyIndexes: file_relo_protocol_lesson_get_proto_depIdxs,
		MessageInfos:      file_relo_protocol_lesson_get_proto_msgTypes,
	}.Build()
	File_relo_protocol_lesson_get_proto = out.File
	file_relo_protocol_lesson_get_proto_rawDesc = nil
	file_relo_protocol_lesson_get_proto_goTypes = nil
	file_relo_protocol_lesson_get_proto_depIdxs = nil
}
