// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/protocol/user/get.proto

package user

import (
	role "github.com/reloclass/core/role"
	user "github.com/reloclass/core/user"
	vo "github.com/reloclass/protocol/vo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取学校用户信息请求
type GetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户id
	// @gotags: param:"userId" json:"userId,string" validate:"required"
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"userId,string" param:"userId" validate:"required"`
	// 角色id
	// @gotags: param:"roleId" json:"roleId,string"
	RoleId role.Type `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3,enum=relo.core.role.Type" json:"roleId,string" param:"roleId"`
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_user_get_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_user_get_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_user_get_proto_rawDescGZIP(), []int{0}
}

func (x *GetReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetReq) GetRoleId() role.Type {
	if x != nil {
		return x.RoleId
	}
	return role.Type_TYPE_UNSPECIFIED
}

// 分页获取用戶信息请求
type GetsByPagingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 当前页
	// @gotags: query:"page" default:"1" validate:"min=1"
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty" query:"page" default:"1" validate:"min=1"`
	// 每页大小
	// @gotags: query:"perPage" default:"20" validate:"min=1"
	Size int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty" query:"perPage" default:"20" validate:"min=1"`
	// 查询关键字
	// @gotags: json:"keyword"
	Keyword string `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword"`
	// 排序规则
	// @gotags: query:"sortOrder" default:"DESC" validate:"oneof=asc ASC ascending ASCENDING desc DESC descending DESCENDING"
	Order string `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty" query:"sortOrder" default:"DESC" validate:"oneof=asc ASC ascending ASCENDING desc DESC descending DESCENDING"`
	// 排序字段
	// @gotags: query:"sortField" default:"created_at" validate:"oneof=created_at updated_at"
	Sort string `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty" query:"sortField" default:"created_at" validate:"oneof=created_at updated_at"`
	//状态 (0-启用,1-停用,2-all)
	Status user.Status `protobuf:"varint,7,opt,name=status,proto3,enum=relo.core.user.Status" json:"status,omitempty"`
	// 角色Id
	// @gotags: json:"roleId,string"
	RoleId role.Type `protobuf:"varint,8,opt,name=role_id,json=roleId,proto3,enum=relo.core.role.Type" json:"roleId,string"`
}

func (x *GetsByPagingReq) Reset() {
	*x = GetsByPagingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_user_get_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsByPagingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsByPagingReq) ProtoMessage() {}

func (x *GetsByPagingReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_user_get_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsByPagingReq.ProtoReflect.Descriptor instead.
func (*GetsByPagingReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_user_get_proto_rawDescGZIP(), []int{1}
}

func (x *GetsByPagingReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetsByPagingReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetsByPagingReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetsByPagingReq) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *GetsByPagingReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetsByPagingReq) GetStatus() user.Status {
	if x != nil {
		return x.Status
	}
	return user.Status_NORMAL
}

func (x *GetsByPagingReq) GetRoleId() role.Type {
	if x != nil {
		return x.RoleId
	}
	return role.Type_TYPE_UNSPECIFIED
}

// 分页获取用户响应
type GetsBaseByPagingRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 总数
	// @gotags: json:"totalNum"
	TotalNum int64 `protobuf:"varint,2,opt,name=total_num,json=totalNum,proto3" json:"totalNum"`
	// 数据
	Items []*user.Base `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetsBaseByPagingRsp) Reset() {
	*x = GetsBaseByPagingRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_user_get_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsBaseByPagingRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsBaseByPagingRsp) ProtoMessage() {}

func (x *GetsBaseByPagingRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_user_get_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsBaseByPagingRsp.ProtoReflect.Descriptor instead.
func (*GetsBaseByPagingRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_user_get_proto_rawDescGZIP(), []int{2}
}

func (x *GetsBaseByPagingRsp) GetTotalNum() int64 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

func (x *GetsBaseByPagingRsp) GetItems() []*user.Base {
	if x != nil {
		return x.Items
	}
	return nil
}

// 分页获取用户响应
type GetsDetailByPagingRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 总数
	// @gotags: json:"totalNum"
	TotalNum int64 `protobuf:"varint,2,opt,name=total_num,json=totalNum,proto3" json:"totalNum"`
	// 数据
	Details []*vo.UserDetail `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *GetsDetailByPagingRsp) Reset() {
	*x = GetsDetailByPagingRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_user_get_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsDetailByPagingRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsDetailByPagingRsp) ProtoMessage() {}

func (x *GetsDetailByPagingRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_user_get_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsDetailByPagingRsp.ProtoReflect.Descriptor instead.
func (*GetsDetailByPagingRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_user_get_proto_rawDescGZIP(), []int{3}
}

func (x *GetsDetailByPagingRsp) GetTotalNum() int64 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

func (x *GetsDetailByPagingRsp) GetDetails() []*vo.UserDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_relo_protocol_user_get_proto protoreflect.FileDescriptor

var file_relo_protocol_user_get_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x2f, 0x67, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x1a, 0x19, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x72,
	0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x72, 0x65, 0x6c, 0x6f,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x07,
	0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0xdc, 0x01, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x73, 0x42, 0x79, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x72, 0x65,
	0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x72,
	0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x72,
	0x65, 0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x5e, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x73, 0x42, 0x61, 0x73, 0x65, 0x42, 0x79, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x73,
	0x70, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x2a,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x6c, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x52, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d,
	0x12, 0x36, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x76, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x3b, 0x75,
	0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_protocol_user_get_proto_rawDescOnce sync.Once
	file_relo_protocol_user_get_proto_rawDescData = file_relo_protocol_user_get_proto_rawDesc
)

func file_relo_protocol_user_get_proto_rawDescGZIP() []byte {
	file_relo_protocol_user_get_proto_rawDescOnce.Do(func() {
		file_relo_protocol_user_get_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_protocol_user_get_proto_rawDescData)
	})
	return file_relo_protocol_user_get_proto_rawDescData
}

var file_relo_protocol_user_get_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_relo_protocol_user_get_proto_goTypes = []interface{}{
	(*GetReq)(nil),                // 0: relo.protocol.user.GetReq
	(*GetsByPagingReq)(nil),       // 1: relo.protocol.user.GetsByPagingReq
	(*GetsBaseByPagingRsp)(nil),   // 2: relo.protocol.user.GetsBaseByPagingRsp
	(*GetsDetailByPagingRsp)(nil), // 3: relo.protocol.user.GetsDetailByPagingRsp
	(role.Type)(0),                // 4: relo.core.role.Type
	(user.Status)(0),              // 5: relo.core.user.Status
	(*user.Base)(nil),             // 6: relo.core.user.Base
	(*vo.UserDetail)(nil),         // 7: relo.protocol.vo.UserDetail
}
var file_relo_protocol_user_get_proto_depIdxs = []int32{
	4, // 0: relo.protocol.user.GetReq.role_id:type_name -> relo.core.role.Type
	5, // 1: relo.protocol.user.GetsByPagingReq.status:type_name -> relo.core.user.Status
	4, // 2: relo.protocol.user.GetsByPagingReq.role_id:type_name -> relo.core.role.Type
	6, // 3: relo.protocol.user.GetsBaseByPagingRsp.items:type_name -> relo.core.user.Base
	7, // 4: relo.protocol.user.GetsDetailByPagingRsp.details:type_name -> relo.protocol.vo.UserDetail
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_relo_protocol_user_get_proto_init() }
func file_relo_protocol_user_get_proto_init() {
	if File_relo_protocol_user_get_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relo_protocol_user_get_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_user_get_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsByPagingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_user_get_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsBaseByPagingRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_user_get_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsDetailByPagingRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_protocol_user_get_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_protocol_user_get_proto_goTypes,
		DependencyIndexes: file_relo_protocol_user_get_proto_depIdxs,
		MessageInfos:      file_relo_protocol_user_get_proto_msgTypes,
	}.Build()
	File_relo_protocol_user_get_proto = out.File
	file_relo_protocol_user_get_proto_rawDesc = nil
	file_relo_protocol_user_get_proto_goTypes = nil
	file_relo_protocol_user_get_proto_depIdxs = nil
}
