// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/protocol/user/login.proto

package user

import (
	menu "github.com/reloclass/core/menu"
	rpc "github.com/reloclass/protocol/user/rpc"
	vo "github.com/reloclass/protocol/vo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 管理员登录请求
type AdminLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 手机号
	// @gotags: json:"name" validate:"required,printascii"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" validate:"required,printascii"`
	// 密码
	// @gotags: json:"password" validate:"required,printascii,min=8,max=30"
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password" validate:"required,printascii,min=8,max=30"`
}

func (x *AdminLoginReq) Reset() {
	*x = AdminLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_user_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginReq) ProtoMessage() {}

func (x *AdminLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_user_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginReq.ProtoReflect.Descriptor instead.
func (*AdminLoginReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_user_login_proto_rawDescGZIP(), []int{0}
}

func (x *AdminLoginReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 管理员登录响应
type AdminLoginRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// token
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// 服务器时间
	// @gotags: json:"serverTime"
	ServerTime int64 `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"serverTime"`
}

func (x *AdminLoginRsp) Reset() {
	*x = AdminLoginRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_user_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminLoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginRsp) ProtoMessage() {}

func (x *AdminLoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_user_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginRsp.ProtoReflect.Descriptor instead.
func (*AdminLoginRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_user_login_proto_rawDescGZIP(), []int{1}
}

func (x *AdminLoginRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdminLoginRsp) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type BackendLoginRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// token
	// @gotags: json:"token"
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token"`
	// 服务器时间
	// @gotags: json:"serverTime"
	ServerTime int64 `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"serverTime"`
	// 用户信息
	// @gotags: json:"user"
	User *rpc.User `protobuf:"bytes,4,opt,name=user,proto3" json:"user"`
	// 学校信息
	// @gotags: json:"school"
	School *vo.BaseSchool `protobuf:"bytes,5,opt,name=school,proto3" json:"school"`
	// 菜单权限
	// @gotags: json:"auth"
	Auth []*menu.Auth `protobuf:"bytes,6,rep,name=auth,proto3" json:"auth"`
	// 是否第一次登陆
	// @gotags: json:"firstLogin"
	FirstLogin bool `protobuf:"varint,7,opt,name=first_login,json=firstLogin,proto3" json:"firstLogin"`
}

func (x *BackendLoginRsp) Reset() {
	*x = BackendLoginRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_user_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendLoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendLoginRsp) ProtoMessage() {}

func (x *BackendLoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_user_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendLoginRsp.ProtoReflect.Descriptor instead.
func (*BackendLoginRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_user_login_proto_rawDescGZIP(), []int{2}
}

func (x *BackendLoginRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BackendLoginRsp) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *BackendLoginRsp) GetUser() *rpc.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *BackendLoginRsp) GetSchool() *vo.BaseSchool {
	if x != nil {
		return x.School
	}
	return nil
}

func (x *BackendLoginRsp) GetAuth() []*menu.Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *BackendLoginRsp) GetFirstLogin() bool {
	if x != nil {
		return x.FirstLogin
	}
	return false
}

// 客户端登录响应
type ClientLoginRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// token
	// @gotags: json:"token"
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token"`
	// 服务器时间
	// @gotags: json:"serverTime"
	ServerTime int64 `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"serverTime"`
	// 用户信息
	// @gotags: json:"user"
	User *rpc.User `protobuf:"bytes,4,opt,name=user,proto3" json:"user"`
	// 是否第一次登陆
	// @gotags: json:"firstLogin"
	FirstLogin bool `protobuf:"varint,7,opt,name=first_login,json=firstLogin,proto3" json:"firstLogin"`
}

func (x *ClientLoginRsp) Reset() {
	*x = ClientLoginRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_user_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientLoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientLoginRsp) ProtoMessage() {}

func (x *ClientLoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_user_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientLoginRsp.ProtoReflect.Descriptor instead.
func (*ClientLoginRsp) Descriptor() ([]byte, []int) {
	return file_relo_protocol_user_login_proto_rawDescGZIP(), []int{3}
}

func (x *ClientLoginRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ClientLoginRsp) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *ClientLoginRsp) GetUser() *rpc.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ClientLoginRsp) GetFirstLogin() bool {
	if x != nil {
		return x.FirstLogin
	}
	return false
}

// 和教育登录请求
type LoginByAndEduReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ticket
	// @gotags: json:"ticket" validate:"required"
	Ticket string `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket" validate:"required"`
}

func (x *LoginByAndEduReq) Reset() {
	*x = LoginByAndEduReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_protocol_user_login_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginByAndEduReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByAndEduReq) ProtoMessage() {}

func (x *LoginByAndEduReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_protocol_user_login_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByAndEduReq.ProtoReflect.Descriptor instead.
func (*LoginByAndEduReq) Descriptor() ([]byte, []int) {
	return file_relo_protocol_user_login_proto_rawDescGZIP(), []int{4}
}

func (x *LoginByAndEduReq) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

var File_relo_protocol_user_login_proto protoreflect.FileDescriptor

var file_relo_protocol_user_login_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x1a, 0x21, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76, 0x6f, 0x2f, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3f, 0x0a, 0x0d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x46, 0x0a, 0x0d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xfb, 0x01, 0x0a, 0x0f, 0x42,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x6f, 0x6f,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x6f, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x53,
	0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x52, 0x06, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x12, 0x28, 0x0a,
	0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x65,
	0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x9a, 0x01, 0x0a, 0x0e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x2a, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79,
	0x41, 0x6e, 0x64, 0x45, 0x64, 0x75, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x72, 0x65, 0x6c, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x3b, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_protocol_user_login_proto_rawDescOnce sync.Once
	file_relo_protocol_user_login_proto_rawDescData = file_relo_protocol_user_login_proto_rawDesc
)

func file_relo_protocol_user_login_proto_rawDescGZIP() []byte {
	file_relo_protocol_user_login_proto_rawDescOnce.Do(func() {
		file_relo_protocol_user_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_protocol_user_login_proto_rawDescData)
	})
	return file_relo_protocol_user_login_proto_rawDescData
}

var file_relo_protocol_user_login_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_relo_protocol_user_login_proto_goTypes = []interface{}{
	(*AdminLoginReq)(nil),    // 0: relo.protocol.user.AdminLoginReq
	(*AdminLoginRsp)(nil),    // 1: relo.protocol.user.AdminLoginRsp
	(*BackendLoginRsp)(nil),  // 2: relo.protocol.user.BackendLoginRsp
	(*ClientLoginRsp)(nil),   // 3: relo.protocol.user.ClientLoginRsp
	(*LoginByAndEduReq)(nil), // 4: relo.protocol.user.LoginByAndEduReq
	(*rpc.User)(nil),         // 5: relo.protocol.user.rpc.User
	(*vo.BaseSchool)(nil),    // 6: relo.protocol.vo.BaseSchool
	(*menu.Auth)(nil),        // 7: relo.core.menu.Auth
}
var file_relo_protocol_user_login_proto_depIdxs = []int32{
	5, // 0: relo.protocol.user.BackendLoginRsp.user:type_name -> relo.protocol.user.rpc.User
	6, // 1: relo.protocol.user.BackendLoginRsp.school:type_name -> relo.protocol.vo.BaseSchool
	7, // 2: relo.protocol.user.BackendLoginRsp.auth:type_name -> relo.core.menu.Auth
	5, // 3: relo.protocol.user.ClientLoginRsp.user:type_name -> relo.protocol.user.rpc.User
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_relo_protocol_user_login_proto_init() }
func file_relo_protocol_user_login_proto_init() {
	if File_relo_protocol_user_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relo_protocol_user_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_user_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminLoginRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_user_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendLoginRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_user_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientLoginRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_protocol_user_login_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginByAndEduReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_protocol_user_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_protocol_user_login_proto_goTypes,
		DependencyIndexes: file_relo_protocol_user_login_proto_depIdxs,
		MessageInfos:      file_relo_protocol_user_login_proto_msgTypes,
	}.Build()
	File_relo_protocol_user_login_proto = out.File
	file_relo_protocol_user_login_proto_rawDesc = nil
	file_relo_protocol_user_login_proto_goTypes = nil
	file_relo_protocol_user_login_proto_depIdxs = nil
}
