// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/protocol/user/rpc.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_relo_protocol_user_rpc_proto protoreflect.FileDescriptor

var file_relo_protocol_user_rpc_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x1a, 0x1d, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x21, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x67, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x61, 0x64, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x21, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0xa3, 0x06, 0x0a, 0x03, 0x52, 0x70, 0x63, 0x12,
	0x4e, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1b, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x1b, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x4e, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x72, 0x65,
	0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x72,
	0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x45, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1c, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x77, 0x64, 0x12, 0x20, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x77, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x77, 0x64, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x65, 0x74, 0x50, 0x77, 0x64, 0x12, 0x1f, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x50, 0x77, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x65,
	0x74, 0x50, 0x77, 0x64, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x1b, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x48, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x2e, 0x72,
	0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x72, 0x65, 0x6c,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x11, 0x41, 0x64,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12,
	0x1e, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x1e, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x51, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x20,
	0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x20, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x4e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x22, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x4e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74,
	0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x29, 0x5a,
	0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x3b, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_relo_protocol_user_rpc_proto_goTypes = []interface{}{
	(*CodeReq)(nil),        // 0: relo.protocol.user.CodeReq
	(*RegisterReq)(nil),    // 1: relo.protocol.user.RegisterReq
	(*LoginReq)(nil),       // 2: relo.protocol.user.LoginReq
	(*UpdatePwdReq)(nil),   // 3: relo.protocol.user.UpdatePwdReq
	(*ResetPwdReq)(nil),    // 4: relo.protocol.user.ResetPwdReq
	(*UserReq)(nil),        // 5: relo.protocol.user.UserReq
	(*UsersReq)(nil),       // 6: relo.protocol.user.UsersReq
	(*AddUserReq)(nil),     // 7: relo.protocol.user.AddUserReq
	(*SetAvatarReq)(nil),   // 8: relo.protocol.user.SetAvatarReq
	(*SetNicknameReq)(nil), // 9: relo.protocol.user.SetNicknameReq
	(*CodeRsp)(nil),        // 10: relo.protocol.user.CodeRsp
	(*RegisterRsp)(nil),    // 11: relo.protocol.user.RegisterRsp
	(*LoginRsp)(nil),       // 12: relo.protocol.user.LoginRsp
	(*UpdatePwdRsp)(nil),   // 13: relo.protocol.user.UpdatePwdRsp
	(*ResetPwdRsp)(nil),    // 14: relo.protocol.user.ResetPwdRsp
	(*UserRsp)(nil),        // 15: relo.protocol.user.UserRsp
	(*UsersRsp)(nil),       // 16: relo.protocol.user.UsersRsp
	(*AddUserRsp)(nil),     // 17: relo.protocol.user.AddUserRsp
	(*SetAvatarRsp)(nil),   // 18: relo.protocol.user.SetAvatarRsp
	(*SetNicknameRsp)(nil), // 19: relo.protocol.user.SetNicknameRsp
}
var file_relo_protocol_user_rpc_proto_depIdxs = []int32{
	0,  // 0: relo.protocol.user.Rpc.VerificationCode:input_type -> relo.protocol.user.CodeReq
	1,  // 1: relo.protocol.user.Rpc.Register:input_type -> relo.protocol.user.RegisterReq
	2,  // 2: relo.protocol.user.Rpc.Login:input_type -> relo.protocol.user.LoginReq
	3,  // 3: relo.protocol.user.Rpc.UpdatePwd:input_type -> relo.protocol.user.UpdatePwdReq
	4,  // 4: relo.protocol.user.Rpc.ResetPwd:input_type -> relo.protocol.user.ResetPwdReq
	5,  // 5: relo.protocol.user.Rpc.GetUser:input_type -> relo.protocol.user.UserReq
	6,  // 6: relo.protocol.user.Rpc.GetUsers:input_type -> relo.protocol.user.UsersReq
	7,  // 7: relo.protocol.user.Rpc.AddUserIfNotExist:input_type -> relo.protocol.user.AddUserReq
	8,  // 8: relo.protocol.user.Rpc.SetAvatar:input_type -> relo.protocol.user.SetAvatarReq
	9,  // 9: relo.protocol.user.Rpc.SetNickname:input_type -> relo.protocol.user.SetNicknameReq
	10, // 10: relo.protocol.user.Rpc.VerificationCode:output_type -> relo.protocol.user.CodeRsp
	11, // 11: relo.protocol.user.Rpc.Register:output_type -> relo.protocol.user.RegisterRsp
	12, // 12: relo.protocol.user.Rpc.Login:output_type -> relo.protocol.user.LoginRsp
	13, // 13: relo.protocol.user.Rpc.UpdatePwd:output_type -> relo.protocol.user.UpdatePwdRsp
	14, // 14: relo.protocol.user.Rpc.ResetPwd:output_type -> relo.protocol.user.ResetPwdRsp
	15, // 15: relo.protocol.user.Rpc.GetUser:output_type -> relo.protocol.user.UserRsp
	16, // 16: relo.protocol.user.Rpc.GetUsers:output_type -> relo.protocol.user.UsersRsp
	17, // 17: relo.protocol.user.Rpc.AddUserIfNotExist:output_type -> relo.protocol.user.AddUserRsp
	18, // 18: relo.protocol.user.Rpc.SetAvatar:output_type -> relo.protocol.user.SetAvatarRsp
	19, // 19: relo.protocol.user.Rpc.SetNickname:output_type -> relo.protocol.user.SetNicknameRsp
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_relo_protocol_user_rpc_proto_init() }
func file_relo_protocol_user_rpc_proto_init() {
	if File_relo_protocol_user_rpc_proto != nil {
		return
	}
	file_relo_protocol_user_code_proto_init()
	file_relo_protocol_user_register_proto_init()
	file_relo_protocol_user_login_proto_init()
	file_relo_protocol_user_get_proto_init()
	file_relo_protocol_user_avatar_proto_init()
	file_relo_protocol_user_add_proto_init()
	file_relo_protocol_user_password_proto_init()
	file_relo_protocol_user_nickname_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_protocol_user_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relo_protocol_user_rpc_proto_goTypes,
		DependencyIndexes: file_relo_protocol_user_rpc_proto_depIdxs,
	}.Build()
	File_relo_protocol_user_rpc_proto = out.File
	file_relo_protocol_user_rpc_proto_rawDesc = nil
	file_relo_protocol_user_rpc_proto_goTypes = nil
	file_relo_protocol_user_rpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RpcClient is the client API for Rpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RpcClient interface {
	// 获取验证码
	VerificationCode(ctx context.Context, in *CodeReq, opts ...grpc.CallOption) (*CodeRsp, error)
	// 注册
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRsp, error)
	// 登陆
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRsp, error)
	// 修改密码
	UpdatePwd(ctx context.Context, in *UpdatePwdReq, opts ...grpc.CallOption) (*UpdatePwdRsp, error)
	// 重置密码
	ResetPwd(ctx context.Context, in *ResetPwdReq, opts ...grpc.CallOption) (*ResetPwdRsp, error)
	GetUser(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserRsp, error)
	GetUsers(ctx context.Context, in *UsersReq, opts ...grpc.CallOption) (*UsersRsp, error)
	AddUserIfNotExist(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserRsp, error)
	SetAvatar(ctx context.Context, in *SetAvatarReq, opts ...grpc.CallOption) (*SetAvatarRsp, error)
	SetNickname(ctx context.Context, in *SetNicknameReq, opts ...grpc.CallOption) (*SetNicknameRsp, error)
}

type rpcClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcClient(cc grpc.ClientConnInterface) RpcClient {
	return &rpcClient{cc}
}

func (c *rpcClient) VerificationCode(ctx context.Context, in *CodeReq, opts ...grpc.CallOption) (*CodeRsp, error) {
	out := new(CodeRsp)
	err := c.cc.Invoke(ctx, "/relo.protocol.user.Rpc/VerificationCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRsp, error) {
	out := new(RegisterRsp)
	err := c.cc.Invoke(ctx, "/relo.protocol.user.Rpc/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRsp, error) {
	out := new(LoginRsp)
	err := c.cc.Invoke(ctx, "/relo.protocol.user.Rpc/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) UpdatePwd(ctx context.Context, in *UpdatePwdReq, opts ...grpc.CallOption) (*UpdatePwdRsp, error) {
	out := new(UpdatePwdRsp)
	err := c.cc.Invoke(ctx, "/relo.protocol.user.Rpc/UpdatePwd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) ResetPwd(ctx context.Context, in *ResetPwdReq, opts ...grpc.CallOption) (*ResetPwdRsp, error) {
	out := new(ResetPwdRsp)
	err := c.cc.Invoke(ctx, "/relo.protocol.user.Rpc/ResetPwd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) GetUser(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserRsp, error) {
	out := new(UserRsp)
	err := c.cc.Invoke(ctx, "/relo.protocol.user.Rpc/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) GetUsers(ctx context.Context, in *UsersReq, opts ...grpc.CallOption) (*UsersRsp, error) {
	out := new(UsersRsp)
	err := c.cc.Invoke(ctx, "/relo.protocol.user.Rpc/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) AddUserIfNotExist(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserRsp, error) {
	out := new(AddUserRsp)
	err := c.cc.Invoke(ctx, "/relo.protocol.user.Rpc/AddUserIfNotExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) SetAvatar(ctx context.Context, in *SetAvatarReq, opts ...grpc.CallOption) (*SetAvatarRsp, error) {
	out := new(SetAvatarRsp)
	err := c.cc.Invoke(ctx, "/relo.protocol.user.Rpc/SetAvatar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) SetNickname(ctx context.Context, in *SetNicknameReq, opts ...grpc.CallOption) (*SetNicknameRsp, error) {
	out := new(SetNicknameRsp)
	err := c.cc.Invoke(ctx, "/relo.protocol.user.Rpc/SetNickname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcServer is the server API for Rpc service.
type RpcServer interface {
	// 获取验证码
	VerificationCode(context.Context, *CodeReq) (*CodeRsp, error)
	// 注册
	Register(context.Context, *RegisterReq) (*RegisterRsp, error)
	// 登陆
	Login(context.Context, *LoginReq) (*LoginRsp, error)
	// 修改密码
	UpdatePwd(context.Context, *UpdatePwdReq) (*UpdatePwdRsp, error)
	// 重置密码
	ResetPwd(context.Context, *ResetPwdReq) (*ResetPwdRsp, error)
	GetUser(context.Context, *UserReq) (*UserRsp, error)
	GetUsers(context.Context, *UsersReq) (*UsersRsp, error)
	AddUserIfNotExist(context.Context, *AddUserReq) (*AddUserRsp, error)
	SetAvatar(context.Context, *SetAvatarReq) (*SetAvatarRsp, error)
	SetNickname(context.Context, *SetNicknameReq) (*SetNicknameRsp, error)
}

// UnimplementedRpcServer can be embedded to have forward compatible implementations.
type UnimplementedRpcServer struct {
}

func (*UnimplementedRpcServer) VerificationCode(context.Context, *CodeReq) (*CodeRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerificationCode not implemented")
}
func (*UnimplementedRpcServer) Register(context.Context, *RegisterReq) (*RegisterRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedRpcServer) Login(context.Context, *LoginReq) (*LoginRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedRpcServer) UpdatePwd(context.Context, *UpdatePwdReq) (*UpdatePwdRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePwd not implemented")
}
func (*UnimplementedRpcServer) ResetPwd(context.Context, *ResetPwdReq) (*ResetPwdRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPwd not implemented")
}
func (*UnimplementedRpcServer) GetUser(context.Context, *UserReq) (*UserRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedRpcServer) GetUsers(context.Context, *UsersReq) (*UsersRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedRpcServer) AddUserIfNotExist(context.Context, *AddUserReq) (*AddUserRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserIfNotExist not implemented")
}
func (*UnimplementedRpcServer) SetAvatar(context.Context, *SetAvatarReq) (*SetAvatarRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAvatar not implemented")
}
func (*UnimplementedRpcServer) SetNickname(context.Context, *SetNicknameReq) (*SetNicknameRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNickname not implemented")
}

func RegisterRpcServer(s *grpc.Server, srv RpcServer) {
	s.RegisterService(&_Rpc_serviceDesc, srv)
}

func _Rpc_VerificationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).VerificationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relo.protocol.user.Rpc/VerificationCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).VerificationCode(ctx, req.(*CodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relo.protocol.user.Rpc/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relo.protocol.user.Rpc/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_UpdatePwd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePwdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).UpdatePwd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relo.protocol.user.Rpc/UpdatePwd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).UpdatePwd(ctx, req.(*UpdatePwdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_ResetPwd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPwdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).ResetPwd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relo.protocol.user.Rpc/ResetPwd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).ResetPwd(ctx, req.(*ResetPwdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relo.protocol.user.Rpc/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).GetUser(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relo.protocol.user.Rpc/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).GetUsers(ctx, req.(*UsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_AddUserIfNotExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).AddUserIfNotExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relo.protocol.user.Rpc/AddUserIfNotExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).AddUserIfNotExist(ctx, req.(*AddUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_SetAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAvatarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).SetAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relo.protocol.user.Rpc/SetAvatar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).SetAvatar(ctx, req.(*SetAvatarReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_SetNickname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNicknameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).SetNickname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relo.protocol.user.Rpc/SetNickname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).SetNickname(ctx, req.(*SetNicknameReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "relo.protocol.user.Rpc",
	HandlerType: (*RpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerificationCode",
			Handler:    _Rpc_VerificationCode_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Rpc_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Rpc_Login_Handler,
		},
		{
			MethodName: "UpdatePwd",
			Handler:    _Rpc_UpdatePwd_Handler,
		},
		{
			MethodName: "ResetPwd",
			Handler:    _Rpc_ResetPwd_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Rpc_GetUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _Rpc_GetUsers_Handler,
		},
		{
			MethodName: "AddUserIfNotExist",
			Handler:    _Rpc_AddUserIfNotExist_Handler,
		},
		{
			MethodName: "SetAvatar",
			Handler:    _Rpc_SetAvatar_Handler,
		},
		{
			MethodName: "SetNickname",
			Handler:    _Rpc_SetNickname_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relo/protocol/user/rpc.proto",
}
